# Generated by Django 2.2.26 on 2022-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_cycledata"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycledata",
            name="lastStartDay",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="cycledata",
            name="periodLength",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
