# Generated by Django 2.2.26 on 2022-04-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20220411_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycledata",
            name="cycleData",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycledata_cycleData",
                to="home.CycleData",
            ),
        ),
    ]
