# Generated by Django 2.2.26 on 2022-04-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cycledata_cycledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycledata',
            name='cycleData',
        ),
    ]
