# Generated by Django 2.2.26 on 2022-04-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cycledata_cycledata'),
        ('users', '0002_auto_20220411_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cycleData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cycleData', to='home.CycleData'),
        ),
    ]
